  

name: CI
on:
  push:
    branches: [ second ]
  pull_request:
    branches: [ second ]
  workflow_dispatch:

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the code
        uses: actions/checkout@v2
        
#Single line commnad
      - name: Run single-line script
        run: echo hello world!
        
 # Multi-line command
       - name: Run multi-line script
        run: |
        echo first line,
        echo second line
        
